### ISSUE TITLE
Block IP overseas and Record User IP

### ISSUE THREAD

**Issue by pursue503** [we-are-dj/server#41]
### 👋  이슈 내용

새벽 5시경 서버로 요청이 들어옴 하지만 존재하지 않는 URL + 특수문자로 인한 에러 발생
```
java.lang.IllegalArgumentException: Invalid character found in the request target [/index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 ]. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:494) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:269) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) [tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.48.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.48.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]

```

검색해보니 중국 PHP 프레임워크를 사용하는 서버로 공격을 하는 요청

### 해결

1. 서버에 접속하는 유저의 IP를 남기는 로그 생성
2. 서버에서 해외 아이피 차단

[참고 링크](https://cybersectrend.tistory.com/110)

### 🎇 기대 결과

1. 서버에 어느 IP로 접속했는지 확인이가능
2. 해외 유저는 접속 불가능

**Comment by pursue503** [comment]
[해외 IP 차단](https://blog.tomclansys.com/7)

```bash
#!/bin/bash
# china ip ban

DATA=./GeoIPCountryWhois.csv
IPT=/sbin/iptables

for IPRANGE in `egrep "China" $DATA | cut -d, -f1,2 | sed -e 's/"//g' | sed -e 's/,/-/g'`
do
        $IPT -A INPUT -p all -m iprange --src-range $IPRANGE -j DROP
        echo "$IPRANGE banned. " 
done

# sudo iptables -L

echo -e "\n\n\tall China ip banned!\n\n"


```

해외 IP 차단

**Comment by pursue503** [comment]
User IP 기록

```
2021-08-10 20:57:42.088  INFO 15144 --- [nio-8080-exec-1] com.dj.server.common.aop.LoggingAop      : {"data":[{"nickName":"홍길동","memberSnsId":"12ㅐㅁ차"}],"className":"com.dj.server.test.controller.AopController","methodName":"testAop","userIp":"127.0.0.1"}
2021-08-10 20:57:42.095  INFO 15144 --- [nio-8080-exec-1] com.dj.server.common.aop.LoggingAop      : {"data":{"nickName":"홍길동","memberSnsId":"12ㅐㅁ차"},"message":"SUCCESS","httpStatus":"OK"}
```

**Comment by pursue503** [comment]
서버에서 IP가 올바르게 확인되는거를 기록합니다.

```
2021-08-10 21:11:52.766  INFO 29998 --- [nio-8080-exec-3] com.dj.server.common.aop.LoggingAop      : {"data":[],"className":"com.dj.server.test.controller.CorsController","methodName":"testCorsGet","userIp":"183.101.153.140"}
```

**Comment by pursue503** [comment]
차단이 안된걸 확인 이슈를 다시 엽니다
AOP 단에서 IP체크를 하면 안되고
exception 을 잡던가 해야할거 같습니다.
```
2021-08-10 21:40:39.569  INFO 29998 --- [nio-8080-exec-8] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the request target [/index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 ]. The valid characters are defined in RFC 7230 and RFC 3986
```

**Comment by pursue503** [comment]
서버에 접속하는 외부 IP는 차단이 완료
웹 서버 접속만 차단하면 될거 같습니다.

**Comment by chaenabi** [comment]
웹 서버 접속 차단을 위한 브랜치를 feature/ipban 으로 통일하고,
Filter로 처리하는 것이 어떨지 의견드립니다.

**Comment by pursue503** [comment]
해당 이슈는 다른 기능들을 개발 후 진행 하겠습니다.

**Comment by chaenabi** [comment]
존재하지않는 url + 특수문자 에러를 정상적으로 404 처리하였습니다.
이제 유저에게 java trace error log를 노출하는 대신 404.html가 보여지게 됩니다.
또한 interceptor에서 해당 유저의 ip를 로그에 기록합니다.

**Comment by chaenabi** [comment]
404.html 대신 #71 요구사항대로 정형화된 에러를 던질수도 있습니다.
그렇게하려면 MainControllerAdvice 클래스의 404에러를 처리하는 메서드에
ErrorResponseDTO를 이용하여 클라이언트측에 전달하기만 하면 됩니다.

**Comment by chaenabi** [comment]
이제 접속국가 제한을 마음대로 설정할 수 있습니다.
현재 접근이 허용된 국가목록은 한국과 미국입니다.
